controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController


mecanum_drive_controller:
  ros__parameters:
    reference_timeout: 0.5

    front_left_wheel_command_joint_name: "lwheel1_Joint"
    rear_left_wheel_command_joint_name: "lwheel2_Joint"
    front_right_wheel_command_joint_name: "rwheel1_Joint"
    rear_right_wheel_command_joint_name: "rwheel2_Joint"

    kinematics:
      base_frame_offset:
        x: 0.0
        y: 0.0
        theta: 0.0
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.17725

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]