### ekf config file
#       
 ###
ekf_filter_node:
    ros__parameters:

        use_sim_time: true
        frequency: 25.0                         #融合里程计输出频率
        sensor_timeout: 0.3                     #传感器超时时间，滤波器生成新输出的最小频率，由传感器频率决定
        two_d_mode: true                        #2D位置状态估计，false为启用3D状态估计
        transform_time_offset: 0.0              #ekf_localization_node 生成变换提供的时间偏移量
        transform_timeout: 0.0                  #指定 TF 侦听器超时时间
        print_diagnostics: false                #输出调试信息
        debug: false                            #输出调试信息到文件
        print_diagnostics: false                #输出日志到iagnostics话题，仅调试时打开
        debug_out_file: /path/to/debug/file.txt #调试文件输出路径，仅当debug为true时生效
        publish_tf: true                        #是否发布 TF变换
        permit_corrected_publication: false     #是否允许旧的传感器数据触发状态更新后重新发布结果
        publish_acceleration: false             # 是否发布加速度状态（nav_msgs/Odometry中的accel字段）
        map_frame: map                          # Defaults to "map" if unspecified
        odom_frame: odom                        # Defaults to "odom" if unspecified
        base_link_frame: base_footprint         # 机器人基坐标系（固连在机器人上）
        world_frame: odom                       # 滤波器的世界坐标系，用于定义状态估计的参考帧 
        
        #轮式里程计（由底盘车轮电机编码器提供）频率约11hz
        odom0: odom_raw
        #测试1
        odom0_config: [false,  false,  false,
                       false, false, false,
                       true,  true,  false,
                       false, false, true,
                       false, false, false]

        odom0_queue_size: 5                     # 订阅 odom0 话题的队列大小
        odom0_nodelay: false
        odom0_differential: false               #是否将绝对位姿数据转换为相对速度（通过差分计算），再用于融合。
        odom0_relative: true                   #是否将传感器的第一个数据作为 “零点”，后续数据以相对值参与融合。
        odom0_pose_use_child_frame: false       #是否使用传感器消息中child_frame_id的初始位姿作为原点，适用于传感器与base_link有固定偏移的场景
        # odom0_pose_rejection_threshold: 20.0  #位姿数据的马氏距离阈值，超过则视为异常值并忽略。
        #odom0_twist_rejection_threshold: 1.5 #twist（速度）数据的马氏距离阈值。
        
        
        #imu数据，由底盘ros控制板提供原始数据，滤波后发布最后数据  频率约25hz
        imu0: imu/data_raw
        #测试1
        imu0_config: [false, false, false,
                      false, false, false ,
                      false, false, false,
                      false, false, true,
                      false, false, false]

        imu0_nodelay: false
        imu0_differential: false
        imu0_relative: false
        imu0_queue_size: 5
        # imu0_pose_rejection_threshold: 20.0                 # Note the difference in parameter names     # 0.8
        # imu0_twist_rejection_threshold: 1.542               # 0.8
        # imu0_linear_acceleration_rejection_threshold: 10.0  #
        imu0_remove_gravitational_acceleration: true           # 是否从 IMU 的加速度数据中移除重力分量。若 IMU 未自动去重力，需启用。
        
        # 根据控制指令预测
        use_control: false                                # 是否在预测阶段使用控制输入（如cmd_vel）生成加速度项，辅助状态预测。
        stamped_control: false                           #指定控制输入的消息类型。true表示接收geometry_msgs/TwistStamped（带时间戳），false表示接收geometry_msgs/Twist（无时间戳）。
        control_timeout: 0.2                             #控制指令的超时时间（秒）。若超过此时长未收到新指令，滤波器将停止使用控制输入进行预测。
        control_config: [true, false, false, false, false, true]  #指定哪些速度维度使用控制输入，对应顺序：[vx, vy, vz, vroll, vpitch, vyaw]，true表示启用该维度的控制输入。
        acceleration_limits: [1.5, 0.0, 0.0, 0.0, 0.0, 3.4]     #各速度维度的最大加速度限制（单位：速度单位 / 秒，如 m/s² 或 rad/s²）
        deceleration_limits: [1.5, 0.0, 0.0, 0.0, 0.0, 4.5]     #各速度维度的最大减速限制（与加速度方向相反的最大变化率）。
        deceleration_gains:  [0.9, 0.9, 0.0, 0.0, 0.0, 1.0] #加速度 / 减速的平滑系数（0~1 之间），用于模拟机器人无法瞬间达到最大加速度 / 减速的特性（如惯性导致的滞后）。
        #数值越接近 1，加速度 / 减速越接近设定的极限值，数值越接近 0，变化越平缓（延迟越大）。

#==========================================================================================================================================================
#传感器协方差，无专业测量设备校准的情况下，建议使用默认值
#
#==========================================================================================================================================================
        #定义滤波器预测模型的过程噪声协方差矩阵（15×15），数值越大，滤波器对预测的信任度越低，更依赖传感器数据。
        process_noise_covariance: [0.05,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.05,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.06,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.03,   0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.03,   0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.06,   0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.025,   0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.025,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.04,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.01,   0.0,    0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.01,   0.0,    0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.02,   0.0,    0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.01,   0.0,    0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.01,   0.0,
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.015]
        # 初始状态估计的协方差矩阵（15×15），数值越大，对初始状态的信任度越低。
        initial_estimate_covariance: [1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,    0.0,     0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     1e-9,    0.0,     0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     1e-9,    0.0,    0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     1e-9,   0.0,    0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    1e-9,   0.0,
                                      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    1e-9]